<script setup lang="ts">
import { name } from "./package.json";

useHead({
  title: "Create Turborepo (vue-nuxt:docs)",
  meta: [{ name: "description", content: "Generated by create turbo" }],
});
</script>

<template>
  <div>
    <h1>{{ name }}</h1>
    <p>Generated by create turbo</p>
    {{ useV3DerivedInfo().nearestUsableTick(10311, 60) }}
  </div>
</template>
